name: Sample Action
on:
  push:
    branch:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print hello world
        shell: bash
        run: echo "hello $name"
        env:
          name: "John"
      - name: call script
        shell: bash
        run: |
          git update-index --chmod=+x ./.github/scripts/script.sh
          ./.github/scripts/script.sh