name: Sample Action
on:
  push:
    branch:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print hello world
        shell: bash
        run: echo "hello $name"
        env:
          name: "John"
      - name: call script
        shell: bash
        run: |
          git update-index --chmod=+x ./.github/scripts/script.sh
          ./.github/scripts/script.sh
      - uses: actions/upload-artifact@v3
        with:
          name: file.txt
          path: ./test-dir/
            
  test-j0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@
        with:
          name: file.txt
          path: ./test-dir/
      - name: print file content
        shell: bash
        run: |
          cd test-dir
          cat file.txt